import { GuideSection } from "@/lib/types";

export const createCaseManualGuide: GuideSection = {
  id: "manual-entry",
  title: "Creating a Case - Manual Entry",
  subtitle: "Manually create and register a new legal case",
  description: "Learn how to manually create a legal case when details are not available in eCourts. The Cases module acts as a central workspace to track ongoing, closed, or pending cases from start to finish.",
  estimatedTime: "5 min",
  totalSteps: 4,
  steps: [
    {
      number: 1,
      title: "Open Cases Module",
      description: "Log in to your OctoGenie account and click on 'Cases' from the left-hand menu.",
      image: "/assets/cases/Cases%20-%20option%20in%20the%20left%20Menu.png",
      imageAlt: "Cases navigation",
    },
    {
      number: 2,
      title: "Start New Case Creation",
      description: "Click the '+ Add New Case' button at the top-right corner and select 'Manual Entry' from the dropdown.",
      image: "/assets/cases/Case-Add%20New%20Case.png",
      imageAlt: "Add New Case dropdown",
    },
    {
      number: 3,
      title: "Select Court Type",
      description: "Choose the appropriate court type: District Court (for District, State, or Lower Courts) or Supreme Court.",
      image: "/assets/cases/Cases%20(Select%20Court%20Type).png",
      imageAlt: "Court type selection",
    },
    {
      number: 4,
      title: "Enter Case Details",
      description: "Fill in the case information manually, upload documents, and assign lawyers. Click 'Create Case' to finalize.",
      image: "/assets/cases/Cases%20-%20Post%20updating%20details%20(Click%20Create%20Case%20Button).png",
      imageAlt: "Case details form",
      expectedOutcome: "The case is successfully created manually and appears in your cases list.",
      isLast: true,
    },
  ],
};

export const createCaseFromECourtGuide: GuideSection = {
  id: "ecourt",
  title: "Creating a Case - From eCourt",
  subtitle: "Import a case from eCourt database",
  description: "Search and import case details directly from the eCourts system to reduce manual data entry. Sync status, court records, and parties involved directly from official databases.",
  estimatedTime: "5 min",
  totalSteps: 8,
  steps: [
    {
      number: 1,
      title: "Navigate to eCourt Search",
      description: "From the Cases module, click '+ Add New Case' and select 'From eCourt'.",
      image: "/assets/cases/Case-Add%20New%20Case.png",
      imageAlt: "Cases navigation",
    },
    {
      number: 2,
      title: "Select Court Type",
      description: "Choose between District Courts (default) or Supreme Court on the search screen.",
      image: "/assets/cases/Cases%20(Select%20Court%20Type).png",
      imageAlt: "Court type selection",
    },
    {
      number: 3,
      title: "Select Location Details",
      description: "Select the State, District, and Court Complex. Note that Court Complex selection is mandatory.",
      image: "/assets/cases/Cases%20-eCourt%20Search.png",
      imageAlt: "Location details",
    },
    {
      number: 4,
      title: "Choose Search Method",
      description: "Select a search method: Case Number, Advocate Name/Number, FIR Number, Act Type, or CNR Number.",
      image: "/assets/cases/Cases%20-eCourt%20Search.png",
      imageAlt: "Search methods",
    },
    {
      number: 5,
      title: "Enter Search Details",
      description: "Enter the required details (e.g., Case Type, Case Number, and Case Year) and click 'Search'.",
      imageAlt: "Search form details",
    },
    {
      number: 6,
      title: "View Search Results",
      description: "The system fetches details from eCourts. Review the displayed information like Case Title and Status.",
      imageAlt: "Search results list",
    },
    {
      number: 7,
      title: "Import Case",
      description: "Select the required case from the results and click 'Import / Create Case'. The system will auto-fill details.",
      imageAlt: "Import button",
    },
    {
      number: 8,
      title: "Complete Case Creation",
      description: "Verify imported details, link to a Client or Matter if required, and click 'Save / Create Case'.",
      image: "/assets/cases/Cases%20-%20Post%20updating%20details%20(Click%20Create%20Case%20Button).png",
      imageAlt: "Finalize case creation",
      expectedOutcome: "The case is successfully imported and synced with eCourt data for tracking.",
      isLast: true,
    },
  ],
};

export const editCaseGuide: GuideSection = {
  id: "edit-case",
  title: "Editing Case Details",
  subtitle: "Keep your case records updated",
  description: "Learn how to modify or update information for an existing case, including lawyer assignments, document storage, and status updates.",
  estimatedTime: "2 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Go to Cases Section",
      description: "Navigate to the Cases section from the main menu.",
      image: "/assets/cases/Cases%20-%20option%20in%20the%20left%20Menu.png",
      imageAlt: "Cases section",
    },
    {
      number: 2,
      title: "Select Specific Case",
      description: "Locate and select the case you want to edit from the list.",
      image: "/assets/cases/Cases%20-View%20Case.png",
      imageAlt: "Case list",
    },
    {
      number: 3,
      title: "View Case",
      description: "Click on 'View Case' to open the case details page.",
      imageAlt: "View case button",
    },
    {
      number: 4,
      title: "Click Edit Button",
      description: "Click the 'Edit' button at the top-right of the Case Details page.",
      image: "/assets/cases/Cases%20-%20Edit%20Case.png",
      imageAlt: "Edit button",
    },
    {
      number: 5,
      title: "Update and Save",
      description: "Modify the necessary case details and click 'Update' or 'Save' to apply changes.",
      image: "/assets/cases/Cases%20-%20Status%20Updation.png",
      imageAlt: "Saving changes",
      expectedOutcome: "Case details are successfully updated in the system.",
      isLast: true,
    },
  ],
};

export const closeCaseGuide: GuideSection = {
  id: "close-case",
  title: "Marking a Case as Closed",
  subtitle: "Finalize completed cases",
  description: "Update the status of a case to reflect its completion. Marking cases as closed helps maintain an organized dashboard and accurate firm records.",
  estimatedTime: "1 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Navigate to Cases",
      description: "Go to the Cases section from the main menu.",
      image: "/assets/cases/Cases%20-%20option%20in%20the%20left%20Menu.png",
      imageAlt: "Cases menu",
    },
    {
      number: 2,
      title: "Select Case",
      description: "Choose the specific case that you wish to close.",
      image: "/assets/cases/Cases%20-View%20Case.png",
      imageAlt: "Select case",
    },
    {
      number: 3,
      title: "Open View Case",
      description: "Click 'View Case' to open details.",
      imageAlt: "View case",
    },
    {
      number: 4,
      title: "Click Edit",
      description: "Click the 'Edit' button to allow status modifications.",
      image: "/assets/cases/Cases%20-%20Edit%20Case.png",
      imageAlt: "Edit button",
    },
    {
      number: 5,
      title: "Set Status to Closed",
      description: "In the 'Assignee & Actions' section, update the status field to 'Closed'.",
      image: "/assets/cases/Cases%20-%20Status%20Updation.png",
      imageAlt: "Status dropdown",
      expectedOutcome: "The case is now marked as Closed and updated in your records.",
      isLast: true,
    },
  ],
};
