import { GuideSection } from "@/lib/types";

export const addClientGuide: GuideSection = {
  id: "add-client",
  title: "Adding a New Client",
  subtitle: "Register and onboard a new client",
  description: "Follow these steps to register a new individual or corporate client. The platform allows you to track personal details, KYC, addresses, and financial records in one place.",
  estimatedTime: "5 min",
  totalSteps: 7,
  steps: [
    {
      number: 1,
      title: "Go to Clients Section",
      description: "Log in to your OctoGenie account. From the left-hand menu, click on Clients. The Clients page will open.",
      image: "/assets/clients/Clients%20-Option%20in%20the%20left%20menu.png",
      imageAlt: "Clients navigation",
    },
    {
      number: 2,
      title: "Click on Add New Client",
      description: "Click the + Add New Client button at the top right corner. The Client Creation Form will open under the Personal Details tab.",
      image: "/assets/clients/Clients%20-%20Add%20New%20Client.png",
      imageAlt: "Add New Client button",
    },
    {
      number: 3,
      title: "Select Client Type",
      description: "Select whether the client is an Individual or a Corporate/Organization.",
      imageAlt: "Client type selection",
    },
    {
      number: 4,
      title: "Enter Personal Details",
      description: "Provide necessary personal details such as name, contact information, and address. Fill in all mandatory fields marked with an asterisk (*).",
      imageAlt: "Client details form",
    },
    {
      number: 5,
      title: "Click on 'Next Button'",
      description: "After filling in the details, click on the 'Next' button at the bottom of the page to proceed to the next section.",
      imageAlt: "Next button",
    },
    {
      number: 6,
      title: "Complete Additional Tabs",
      description: "Continue filling details in other tabs if necessary: Address, KYC Validation, Documents, Client Onboarding, Internal Notes, and Financial Records.",
      image: "/assets/clients/Clients%20-%20View%20Details.png",
      imageAlt: "Additional tabs",
    },
    {
      number: 7,
      title: "Client Record Created",
      description: "Once all details are updated, click on the 'Create Client' button at the bottom right. The client will be successfully created and appear in the Clients List.",
      image: "/assets/clients/Clients%20-%20Post%20updating%20details%20(Create%20Client).png",
      imageAlt: "Create Client button",
      expectedOutcome: "The client record is successfully created and can now be linked to matters, assigned to cases, and used for billing and tracking.",
      isLast: true,
    },
  ],
};

export const editClientGuide: GuideSection = {
  id: "edit-client",
  title: "Editing Client Details",
  subtitle: "Keep client information updated",
  description: "Learn how to update existing client records in OctoGenie.",
  estimatedTime: "2 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Go to Clients Section",
      description: "Navigate to the Clients section from the main menu.",
      image: "/assets/clients/Clients%20-Option%20in%20the%20left%20menu.png",
      imageAlt: "Clients section",
    },
    {
      number: 2,
      title: "Locate Client",
      description: "Go to the specific client you want to edit. You can search for the client using the search bar.",
      imageAlt: "Locate client",
    },
    {
      number: 3,
      title: "Click on View Details",
      description: "Click on 'View Details' to open the client's profile and details.",
      image: "/assets/clients/Clients%20-%20View%20Details.png",
      imageAlt: "View Details button",
    },
    {
      number: 4,
      title: "Click the Edit Button",
      description: "Click the Edit button to enable modification of the record.",
      image: "/assets/clients/Clients%20-Edit.png",
      imageAlt: "Edit button",
    },
    {
      number: 5,
      title: "Update and Save",
      description: "Update the required details and save the changes.",
      imageAlt: "Save changes",
      expectedOutcome: "Client details are successfully updated.",
      isLast: true,
    },
  ],
};

export const uploadClientDocumentsGuide: GuideSection = {
  id: "upload-documents",
  title: "Uploading Documents for Client",
  subtitle: "Manage client-related documents",
  description: "How to upload and manage documents for a client after the profile has been created.",
  estimatedTime: "3 min",
  totalSteps: 7,
  steps: [
    {
      number: 1,
      title: "Navigate to Clients",
      description: "Go to the Clients section from the left-side menu.",
      image: "/assets/clients/Clients%20-Option%20in%20the%20left%20menu.png",
      imageAlt: "Clients section",
    },
    {
      number: 2,
      title: "Select Client",
      description: "Select the client for whom documents need to be uploaded.",
      image: "/assets/clients/Clients%20-%20View%20Details.png",
      imageAlt: "Select client",
    },
    {
      number: 3,
      title: "Click on Documents Tab",
      description: "Click on the Documents tab within the client's profile.",
      imageAlt: "Documents tab",
    },
    {
      number: 4,
      title: "Upload File",
      description: "Under Document Upload, click 'Upload a file' or drag and drop the document into the upload area.",
      imageAlt: "Upload area",
    },
    {
      number: 5,
      title: "Choose Document",
      description: "Choose the required document from your system.",
      imageAlt: "File explorer",
    },
    {
      number: 6,
      title: "Verify Upload",
      description: "Verify that the file is successfully uploaded to the platform.",
      imageAlt: "Upload status",
    },
    {
      number: 7,
      title: "Proceed",
      description: "Click Next to proceed to the next step. Note that uploading documents is optional and multiple documents can be uploaded one by one.",
      imageAlt: "Next button",
      expectedOutcome: "Documents are securely stored and linked to the client's profile for future reference.",
      isLast: true,
    },
  ],
};

export const deleteClientGuide: GuideSection = {
  id: "delete-client",
  title: "Deleting a Client",
  subtitle: "Remove a client record",
  description: "Steps to permanently remove a client record from the OctoGenie platform.",
  estimatedTime: "2 min",
  totalSteps: 6,
  steps: [
    {
      number: 1,
      title: "Log in to OctoGenie",
      description: "Access your account with your credentials.",
      imageAlt: "Login page",
    },
    {
      number: 2,
      title: "Go to Clients Section",
      description: "From the left-side menu, click on Clients.",
      image: "/assets/clients/Clients%20-Option%20in%20the%20left%20menu.png",
      imageAlt: "Clients menu",
    },
    {
      number: 3,
      title: "Open Client Details",
      description: "Search for the client using the search bar or click 'View Details' from the client list.",
      image: "/assets/clients/Clients%20-%20View%20Details.png",
      imageAlt: "Client list view",
    },
    {
      number: 4,
      title: "Click on Delete",
      description: "On the top-right corner of the Client Details page, click the Delete button (red button).",
      image: "/assets/clients/Clients%20-Delete.png",
      imageAlt: "Delete button",
    },
    {
      number: 5,
      title: "Confirm Deletion",
      description: "A confirmation pop-up will appear. Click Confirm / Yes to proceed with deletion.",
      imageAlt: "Confirmation dialog",
    },
    {
      number: 6,
      title: "Client Deleted",
      description: "The client will be permanently removed. You will be redirected back to the Clients List, and the deleted client will no longer appear.",
      imageAlt: "Clients list after deletion",
      expectedOutcome: "The client record is completely removed from the platform.",
      isLast: true,
    },
  ],
};
