import { GuideSection } from "@/lib/types";

export const createMatterGuide: GuideSection = {
  id: "create-matter",
  title: "Creating a New Matter",
  subtitle: "Manage, organize, and track legal tasks",
  description: "A matter is any legal problem or task a client brings to a lawyer. The Matter feature helps you manage everything in one place, including filing lawsuits, drafting contracts, registering trademarks, and giving legal advice.",
  estimatedTime: "5 min",
  totalSteps: 7,
  steps: [
    {
      number: 1,
      title: "Login and Navigation",
      description: "Log in to your OctoGenie account and click on 'Matters' from the left-hand menu.",
      image: "/assets/matters/Matters%20Option%20(Left%20Menu).png",
      imageAlt: "Matters navigation",
    },
    {
      number: 2,
      title: "Add New Matter",
      description: "On the top-right side of the page, click the '+ Add New Matter' button.",
      image: "/assets/matters/Add%20New%20Matter.png",
      imageAlt: "Add New Matter button",
    },
    {
      number: 3,
      title: "Provide Matter Details",
      description: "On the Create New Matter form, click on 'Matter Details' to provide the basic information about the matter.",
      image: "/assets/matters/Create%20a%20New%20Matter%20Screen%20(Matter%20details).png",
      imageAlt: "Matter details tab",
    },
    {
      number: 4,
      title: "Add Parties & Contacts",
      description: "Click on the 'Parties & Contacts' button to add the parties involved and their contact details.",
      imageAlt: "Parties and contacts info",
    },
    {
      number: 5,
      title: "Set Assignment & Status",
      description: "Set the assignment, status, and additional matter details by clicking on the 'Assignment & Status' section.",
      image: "/assets/matters/Matter%20Assignment%20and%20Status.png",
      imageAlt: "Assignment and status tab",
    },
    {
      number: 6,
      title: "Upload Relevant Documents",
      description: "Click on the 'Relevant Documents' section to upload files related to this matter (Optional).",
      imageAlt: "Relevant documents section",
    },
    {
      number: 7,
      title: "Finalize Matter Creation",
      description: "Click on the 'Create Matter' button at the right bottom to finalize.",
      image: "/assets/matters/Post%20updating%20details%20(Click%20on%20Create%20Matter%20Buuton).png",
      imageAlt: "Create Matter button",
      expectedOutcome: "The legal matter is successfully created and appears in your matters list with all contacts and documents attached.",
      isLast: true,
    },
  ],
};

export const linkClientGuide: GuideSection = {
  id: "link-client",
  title: "Linking a Client to a Matter",
  subtitle: "Associate clients with their legal tasks",
  description: "Connect your clients to specific matters for better organization and billing.",
  estimatedTime: "2 min",
  totalSteps: 4,
  steps: [
    {
      number: 1,
      title: "Open Matters",
      description: "Go to the Matter section from the main menu.",
      image: "/assets/matters/Matters%20Option%20(Left%20Menu).png",
      imageAlt: "Matter menu",
    },
    {
      number: 2,
      title: "Access Matter",
      description: "Open the matter to which you want to add a client.",
      imageAlt: "Select matter",
    },
    {
      number: 3,
      title: "Go to Assignment & Status",
      description: "Click on the 'Assignment & Status' tab.",
      image: "/assets/matters/Matter%20Assignment%20and%20Status.png",
      imageAlt: "Assignment section",
    },
    {
      number: 4,
      title: "Select Client",
      description: "From the 'Add Client' field, select the required client from the list.",
      imageAlt: "Client selection field",
      expectedOutcome: "The client is now linked to this matter for tracking and billing.",
      isLast: true,
    },
  ],
};

export const updateMatterStatusGuide: GuideSection = {
  id: "update-status",
  title: "Updating Matter Status",
  subtitle: "Track the progress of your matters",
  description: "Keep your matters organized by updating their current progress status.",
  estimatedTime: "1 min",
  totalSteps: 4,
  steps: [
    {
      number: 1,
      title: "Navigate to Matters",
      description: "Go to the Matter section from the main menu.",
      image: "/assets/matters/Matters%20Option%20(Left%20Menu).png",
      imageAlt: "Matters menu",
    },
    {
      number: 2,
      title: "Open Relevant Matter",
      description: "Open the matter to which you want to update the status.",
      imageAlt: "Open matter",
    },
    {
      number: 3,
      title: "Go to Assignment & Status",
      description: "Click on the 'Assignment & Status' section.",
      image: "/assets/matters/Matter%20Assignment%20and%20Status.png",
      imageAlt: "Assignment tab",
    },
    {
      number: 4,
      title: "Update Status field",
      description: "Update the status from the status field (e.g., Active, Pending, Completed, On Hold).",
      image: "/assets/matters/Matter%20Assignment%20and%20Status.png",
      imageAlt: "Status dropdown",
      expectedOutcome: "The matter status is updated instantly throughout the system.",
      isLast: true,
    },
  ],
};

export const editMatterGuide: GuideSection = {
  id: "edit-matter",
  title: "Editing a Matter",
  subtitle: "Keep matter information up-to-date",
  description: "Learn how to update details for an existing matter.",
  estimatedTime: "2 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Go to Matters",
      description: "Navigate to the Matters section from the main menu.",
      image: "/assets/matters/Matters%20Option%20(Left%20Menu).png",
      imageAlt: "Matters menu",
    },
    {
      number: 2,
      title: "Select Matter",
      description: "Go to the specific matter you want to edit.",
      imageAlt: "Select specific matter",
    },
    {
      number: 3,
      title: "Open Matter Details",
      description: "Click on 'View Matter' to open the matter details page.",
      imageAlt: "Matter details view",
    },
    {
      number: 4,
      title: "Click Edit Button",
      description: "Click the Edit button to enable changes to the matter information.",
      image: "/assets/matters/Edit%20Matter.png",
      imageAlt: "Edit button",
    },
    {
      number: 5,
      title: "Update and Save",
      description: "Update the required matter details and save the changes.",
      imageAlt: "Saving changes",
      expectedOutcome: "The matter record is accurately updated with the new information.",
      isLast: true,
    },
  ],
};

export const bulkUploadGuide: GuideSection = {
  id: "bulk-upload",
  title: "Bulk Uploading Matters",
  subtitle: "Onboard large volumes of data efficiently",
  description: "The Bulk Upload option allows you to upload multiple matters at once using an Excel template, saving time and ensuring consistency.",
  estimatedTime: "10 min",
  totalSteps: 8,
  steps: [
    {
      number: 1,
      title: "Navigate to Matters Module",
      description: "Log in and click on Matters from the left-hand navigation panel.",
      image: "/assets/matters/Matters%20Option%20(Left%20Menu).png",
      imageAlt: "Matters navigation",
    },
    {
      number: 2,
      title: "Click on Bulk Upload",
      description: "On the top-right corner of the Matters page, click the 'Bulk Upload' button.",
      image: "/assets/matters/Matters%20Bulk%20Upload.png",
      imageAlt: "Bulk Upload button",
    },
    {
      number: 3,
      title: "Select Download Template",
      description: "Click on the 'Bulk Upload' option and select 'Download Template' to download the sample Excel file.",
      image: "/assets/matters/Download%20template%20(Matters%20Bulk%20Upload).png",
      imageAlt: "Download template link",
    },
    {
      number: 4,
      title: "Download Excel Template",
      description: "Download the provided Excel template which contains predefined columns required for matter creation.",
      imageAlt: "Excel file download",
    },
    {
      number: 5,
      title: "Fill in Matter Details",
      description: "Enter details for each matter in a separate row. Ensure all mandatory fields are filled correctly following the data format.",
      imageAlt: "Filling spreadsheet",
    },
    {
      number: 6,
      title: "Upload the Completed File",
      description: "Save the Excel file and upload it using the Bulk Upload option.",
      image: "/assets/matters/Matters%20Bulk%20Upload.png",
      imageAlt: "Uploading file",
    },
    {
      number: 7,
      title: "Validate and Submit",
      description: "The system validates the data. If there are errors, correct them and re-upload. Once successful, submit the file.",
      imageAlt: "Validation process",
    },
    {
      number: 8,
      title: "Confirmation",
      description: "Successfully uploaded matters will be created automatically and appear in the Matters list.",
      imageAlt: "New matters in list",
      expectedOutcome: "Multiple matters are created efficiently and ready for management.",
      isLast: true,
    },
  ],
};

export const exportExcelGuide: GuideSection = {
  id: "export",
  title: "Exporting Matters to Excel",
  subtitle: "Offline review and reporting",
  description: "Download matter details into an Excel file for offline review, reporting, or record-keeping.",
  estimatedTime: "2 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Navigate to Matters Section",
      description: "From the left-side menu, click on Matters.",
      image: "/assets/matters/Matters%20Option%20(Left%20Menu).png",
      imageAlt: "Matters section",
    },
    {
      number: 2,
      title: "Review or Filter (Optional)",
      description: "Use the search bar or filters to find specific matters you want to export. Select individual matters using checkboxes if needed.",
      imageAlt: "Filter and selection",
    },
    {
      number: 3,
      title: "Click Export to Excel",
      description: "On the top-right corner of the Matters page, click the 'Export to Excel' button.",
      image: "/assets/matters/Export%20to%20Excel%20(Matters).png",
      imageAlt: "Export button",
    },
    {
      number: 4,
      title: "Download the Excel File",
      description: "The system automatically generates and downloads the Excel file containing the matter details.",
      image: "/assets/matters/Export%20to%20Excel%20(Matters).png",
      imageAlt: "Downloading file",
    },
    {
      number: 5,
      title: "Open and Review",
      description: "Open the downloaded file to view information such as Matter ID, Title, Status, Priority, and more.",
      image: "/assets/matters/Export%20to%20Excel%20(Matters).png",
      imageAlt: "Excel view",
      expectedOutcome: "Matters are exported into an Excel file for easy sharing and documentation.",
      isLast: true,
    },
  ],
};

export const filterMattersGuide: GuideSection = {
  id: "filter-matters",
  title: "Using Filters in Matters",
  subtitle: "Quickly find and organize matters",
  description: "The Filter option helps you narrow down your list based on specific criteria like status, type, priority, and date.",
  estimatedTime: "1 min",
  totalSteps: 6,
  steps: [
    {
      number: 1,
      title: "Go to the Matters Module",
      description: "Click on Matters from the left-hand menu.",
      image: "/assets/matters/Matters%20Option%20(Left%20Menu).png",
      imageAlt: "Matters menu",
    },
    {
      number: 2,
      title: "Click on Add Filter",
      description: "On the top-right of the Matters list, click '+ Add Filter'.",
      image: "/assets/matters/Add%20Filter%20(Matters).png",
      imageAlt: "Add Filter button",
    },
    {
      number: 3,
      title: "Select a Filter Type",
      description: "Choose from options like Status, Matter Type, Priority, Assigned To, Filing Date Range, or Created Date Range.",
      imageAlt: "Filter type list",
    },
    {
      number: 4,
      title: "Apply Filter Criteria",
      description: "Select or enter the required values for the chosen filter. Multiple filters can be applied at once.",
      image: "/assets/matters/Add%20Filter%20(Matters).png",
      imageAlt: "Apply criteria",
    },
    {
      number: 5,
      title: "View Filtered Results",
      description: "The list updates instantly to display only the matters matching your criteria.",
      imageAlt: "Filtered list view",
    },
    {
      number: 6,
      title: "Modify or Clear Filters",
      description: "Change values or remove filters to return to the complete Matters list.",
      imageAlt: "Clear filters",
      expectedOutcome: "Efficiently manage matters by viewing only the most relevant records.",
      isLast: true,
    },
  ],
};
