import { GuideSection } from "@/lib/types";

export const navigateToSettingsGuide: GuideSection = {
  id: "navigate-settings",
  title: "Accessing Platform Settings",
  subtitle: "Configure your OctoGenie environment",
  description: "The Settings section is the central configuration suite used to manage your account, profile details, security, roles, approvals, and system preferences.",
  estimatedTime: "1 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Login and Dashboard",
      description: "Login to the OctoGenie Partner Portal. Go to the top-right corner of your dashboard.",
      image: "/assets/settings/Settings%20-%20Option%20in%20the%20right%20top.png",
      imageAlt: "User profile menu location",
    },
    {
      number: 2,
      title: "Open Account Menu",
      description: "Click on your Profile / Account icon to see the quick actions dropdown.",
      image: "/assets/settings/settings-page2-img1.png",
      imageAlt: "Profile dropdown",
    },
    {
      number: 3,
      title: "Select Settings",
      description: "From the dropdown menu, select 'Settings'.",
    },
    {
      number: 4,
      title: "Review Options",
      description: "The Settings page will open with options like Account, Security, Users & Roles, Approvals, and more.",
      image: "/assets/settings/settings-page3-img1.png",
      imageAlt: "Settings overview page",
    },
    {
      number: 5,
      title: "Navigate to Sub-sections",
      description: "Use the left-side settings menu to switch between different configuration areas.",
      image: "/assets/settings/settings-page3-img2.png",
      imageAlt: "Settings sidebar",
      expectedOutcome: "You are now in the central configuration suite for your firm.",
      isLast: true,
    },
  ],
};

export const manageUsersGuide: GuideSection = {
  id: "users-roles",
  title: "Managing Users & Roles",
  subtitle: "Control team access and hierarchy",
  description: "Add new team members, manage existing users, and assign appropriate roles.",
  estimatedTime: "3 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Open Users & Roles",
      description: "From the Settings sidebar, click on 'Users & Roles'.",
      image: "/assets/settings/Settings%20-%20Users%20%26%20Roles.png",
      imageAlt: "Users section",
    },
    {
      number: 2,
      title: "Invite New User",
      description: "Click on the 'Invite User' button located at the top-right corner of the page.",
      image: "/assets/settings/settings-page4-img1.png",
      imageAlt: "Invite User button",
    },
    {
      number: 3,
      title: "Enter User Details",
      description: "Fill in the required user details: Full Name, Email ID, Phone, and User Type.",
      image: "/assets/settings/settings-page5-img1.png",
      imageAlt: "Invite User form",
    },
    {
      number: 4,
      title: "Assign Role",
      description: "In the 'Role' dropdown, select the predefined role (e.g., Admin, Default Lawyer) for the new user.",
      image: "/assets/settings/settings-page5-img1.png",
      imageAlt: "Role selection dropdown",
    },
    {
      number: 5,
      title: "Send Invitation",
      description: "Click 'Invite User' to submit. The user will receive access based on the assigned role. Note that users can be searched or filtered later.",
      image: "/assets/settings/Settings%20-%20User%20%26%20Roles%20(Filter%20Option).png",
      imageAlt: "Verifying user in list",
      expectedOutcome: "Team members are successfully added with specific access levels.",
      isLast: true,
    },
  ],
};

export const manageRolesPermissionsGuide: GuideSection = {
  id: "roles-permissions",
  title: "Roles & Permissions",
  subtitle: "Granular access control for your firm",
  description: "Define exactly what each role can view, create, edit, or delete in the platform.",
  estimatedTime: "5 min",
  totalSteps: 6,
  steps: [
    {
      number: 1,
      title: "Access Roles",
      description: "From the main Settings menu, go to 'Roles & Permissions'.",
      image: "/assets/settings/Settings%20-%20Roles%20%26%20Permissions.png",
      imageAlt: "Roles list",
    },
    {
      number: 2,
      title: "Create a New Role",
      description: "Click on '+ New Role' at the top-right. Enter the Role Name and an optional Description.",
      image: "/assets/settings/Settings%20-%20Create%20New%20Role.png",
      imageAlt: "New Role button",
    },
    {
      number: 3,
      title: "Configure Hierarchy",
      description: "Navigate to the role you want to set permissions for in the list. Click 'Configure' under the Actions column.",
      image: "/assets/settings/settings-page7-img1.png",
      imageAlt: "Configure action button",
    },
    {
      number: 4,
      title: "Define Permissions",
      description: "The permissions page will show module-wise options. Select permissions like View, Create, Edit, Delete, or Approve.",
      image: "/assets/settings/settings-page8-img1.png",
      imageAlt: "Permissions checkboxes",
    },
    {
      number: 5,
      title: "Enable/Disable responsibilities",
      description: "Toggle the access levels based on the specific responsibilities of that role.",
      image: "/assets/settings/settings-page9-img1.png",
      imageAlt: "Toggling access",
    },
    {
      number: 6,
      title: "Save Configuration",
      description: "Click 'Save / Update' to apply the changes to all users assigned to this role.",
      image: "/assets/settings/Settings%20-%20Configure%20(Roles%20%26%20Permissions).png",
      imageAlt: "Saving roles",
      expectedOutcome: "Secure and organized platform access tailored to your firm's structure.",
      isLast: true,
    },
  ],
};

export const manageApprovalsGuide: GuideSection = {
  id: "approvals",
  title: "Configuring Approvals",
  subtitle: "Maintain oversight on firm activities",
  description: "Set up approval workflows for critical actions like expenses and invoices.",
  estimatedTime: "3 min",
  totalSteps: 5,
  steps: [
    {
      number: 1,
      title: "Open Approvals",
      description: "Click on 'Approvals' under the Settings section menu.",
      image: "/assets/settings/settings-page10-img1.png",
      imageAlt: "Approvals menu",
    },
    {
      number: 2,
      title: "Select Category",
      description: "Choose the action group you wish to configure (e.g., Expenses Approval).",
      image: "/assets/settings/Settings%20-%20Expenses%20Approval%20flow.png",
      imageAlt: "Choosing category",
    },
    {
      number: 3,
      title: "Choose Approval Mode",
      description: "Select between: 'No Approval' (Auto-approved), 'Single' (One designated approver), or 'Multi-Step' (Multiple approval levels).",
      image: "/assets/settings/settings-page11-img1.png",
      imageAlt: "Approval modes",
    },
    {
      number: 4,
      title: "Save Configuration",
      description: "Click 'Save Configuration' to apply the workflow changes.",
      image: "/assets/settings/settings-page11-img1.png",
      imageAlt: "Submit config button",
    },
    {
      number: 5,
      title: "Outcome",
      description: "All future submissions for that category will now follow the selected approval workflow.",
      image: "/assets/settings/Settings%20-%20Approvals%20option%20in%20the%20left%20menu.png",
      imageAlt: "Active workflow",
      expectedOutcome: "Enhanced financial control and compliance for all transactions.",
      isLast: true,
    },
  ],
};

export const otherSettingsGuide: GuideSection = {
  id: "other-settings",
  title: "Preferences, Templates & Support",
  subtitle: "Personalize your experience",
  description: "Configure your platform environment including security, notifications, fees, and language preferences.",
  estimatedTime: "2 min",
  totalSteps: 6,
  steps: [
    {
      number: 1,
      title: "Account & Profile",
      description: "Manage personal and organization profile details. Keep your firm's contact information and branding up to date.",
      image: "/assets/settings/Settings%20-%20Account.png",
      imageAlt: "Account tab",
    },
    {
      number: 2,
      title: "Security & 2FA",
      description: "Manage password updates, enable Two-Factor Authentication, and review your Login History to ensure your account remains safe.",
      image: "/assets/settings/Settings%20-%20Security.png",
      imageAlt: "Security tab",
    },
    {
      number: 3,
      title: "Notifications Control",
      description: "Set your preferences for System alerts, Email notifications, and Activity updates to stay informed without getting overwhelmed.",
      image: "/assets/settings/Settings%20-%20Remaining%20Options.png",
      imageAlt: "Notification settings",
    },
    {
      number: 4,
      title: "Fee Management & Templates",
      description: "Configure service fees and charges. Manage predefined formats for documents and communications in the 'Templates' section.",
      image: "/assets/settings/Settings%20-%20Remaining%20Options.png",
      imageAlt: "Fee and template config",
    },
    {
      number: 5,
      title: "Language & Appearance",
      description: "Select your preferred language and adjust the platform theme and look-and-feel to match your workflow.",
      image: "/assets/settings/Settings%20-%20Remaining%20Options.png",
      imageAlt: "UI personalization",
    },
    {
      number: 6,
      title: "Help & Support",
      description: "Access support resources, raise queries, or review FAQs. Get assistance whenever you face technical or procedural issues.",
      image: "/assets/settings/Settings%20-%20Remaining%20Options.png",
      imageAlt: "Support portal",
      expectedOutcome: "Your OctoGenie environment is perfectly tailored to your firm's specific needs with full security and support awareness.",
      isLast: true,
    },
  ],
};
